version: "3.9"
services: 
  mtm_test:
    container_name: "mtm_compose_test"
    ports:
      - "80:9000"
    build:
      context: ./backend/api-service
      dockerfile: Dockerfile
    depends_on:
      - mtm_mongo
    environment:
      - "JAVA_OPTS=-Xms128m -Xmx256m"
      - "SPRING_DATA_MONGODB_URI=mongodb://mtm_mongo:27017/mtm_dev"
      - "SERVER_PORT=9000"
      - "SPRING_APPLICATION_NAME=mtm_test_deployment"
      - "SPRING_PROFILES_ACTIVE=${MTM_ACTIVE_PROFILE}"
    image: mtm_compose_test:0.1
  mtm_mongo:
    container_name: "mtm_compose_mongo"
    ports:
      - "27017:27017"
    image: mongo
  mtm_mongo_express:
    image: mongo-express
    container_name: "m_express"
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_URL=mongodb://mtm_mongo:27017"
    depends_on:
      - mtm_mongo

