spring.data.mongodb.uri=mongodb+srv://spring_micro_time_manager:qAn7COcumzqcU1Fe@cluster-1.0nqvgu2.mongodb.net/micro-time-management?retryWrites=true&w=majority
#qAn7COcumzqcU1Fe
logging.file.path=/
logging.file.name=micro-time-management.log
server.servlet.context-path=/api/v1