server:
  servlet:
    context-path: /mtm
  port: 18080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
springdoc:
  swagger-ui:
    default-model-expand-depth: 5
    default-models-expand-depth: -1
  show-actuator: true
logging:
  file:
    name: ${LOG_FILE_PROPERTIES}
jwt:
  secret: ${MTM_JWT_SECRET}
