server:
  servlet:
    context-path: /mtm-dev
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mtm_dev
springdoc:
  swagger-ui:
    default-model-expand-depth: 5
    default-models-expand-depth: -1
    use-root-path: true
  show-actuator: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: log/mtm_test.log
jwt:
  secret: "jnv89h4qp98hon98q34opf0934ur0f2iqk40if0935ut09843u908fu4309gh03589rjf0934j0fj304jf930j094f0934o"